- Gemfile
- README.md
- README.md.erb
- Rakefile
- lib/twitter_cldr/resources/postal_codes_importer.rb
- resources/shared/postal_codes.yml
See #165 and #166. Basically postcode data has been deprecated in CLDR v27 because nobody was maintaining it. This PR pulls the data from an API instead.
> Pull postcodes from API

- lib/twitter_cldr/utils.rb
- lib/twitter_cldr/utils/file_system_trie.rb
- spec/utils/file_system_trie_spec.rb
FileSystemTrie is a trie that stores `Marshal::dump`ed nodes on disk.
--
This PR is part of a larger effort to refactor our Unicode properties support. See #170.
> Adding the FileSystemTrie class

- lib/twitter_cldr/utils/range_set.rb
- spec/utils/range_set_spec.rb
Minor improvements to `RangeSet`.
--
This PR is part of a larger effort to refactor our Unicode properties support. See #170.
> Minor improvements to RangeSet

- README.md
- README.md.erb
- lib/twitter_cldr/localized/localized_symbol.rb
- spec/localized/localized_symbol_spec.rb
Added the method `as_territory` for use along with `localize`, which simplifies the call to `TwitterCldr::Shared::Territories::from_territory_code_for_locale()`, this way, a user can, for example, obtain the territory name for `gb` in Portuguese by using `:gb.localize(:pt).as_territory`.
The documentation *(README.md and README.md.erb)* now have a section called `World Territories` which describes this new method along with the use of the other territory localization methods present at `twitter-cldr-rb/lib/twitter_cldr/shared/territories.rb`.
A test for the new `as_territory` method, was added to the Ruby spec test file `twitter-cldr-rb/spec/localized/localized_symbol_spec.rb`.
-----
Solves issue #181
> Adds method "as_territory" and document territory methods

- lib/twitter_cldr/parsers/parser.rb
- lib/twitter_cldr/parsers/unicode_regex/character_class.rb
- lib/twitter_cldr/parsers/unicode_regex/character_range.rb
- lib/twitter_cldr/parsers/unicode_regex/character_set.rb
- lib/twitter_cldr/parsers/unicode_regex_parser.rb
- lib/twitter_cldr/shared/properties_database.rb
- lib/twitter_cldr/tokenizers/tokenizer.rb
- lib/twitter_cldr/tokenizers/unicode_regex/unicode_regex_tokenizer.rb
- lib/twitter_cldr/utils/range_set.rb
- spec/shared/code_point_spec.rb
- spec/shared/properties_database_spec.rb
- spec/shared/unicode_regex_spec.rb
Unicode regexes currently have the following issues:
1. The regex `/[[:L:][:White_Space:]]/` raises a `UnicodeRegexParserError` because it thinks `White_Space` isn't a valid unicode property (surprise: it is).
2. Putting in an equals sign avoids the error, but doesn't correctly match word and whitespace characters. `'a b c _ d'.gsub(UnicodeRegex.compile('[[:L:][:=White_Space:]]'), '')` returns `" b   d"`, expected `"_"`
3. While it is true that negating the regex matches the opposite characters in the test string, the wrong characters are matched. `'a b c _ d'.gsub(UnicodeRegex.compile('[^[:L:][:=White_Space:]]'), '')` returns `"ac_"`, expected: `"a b c  d"`
4. A dash as the first character of a character class is treated as a range. I had previously thought this to be correct behavior, …
> Fix invalid unicode regex behavior

- README.md.erb
I hope I got this right. I'm guessing the `.erb` builds the ordinary readme, is that right?
> Example with calendar data

- twitter_cldr.gemspec
Gem `json` since 2.0 requires Ruby ~> 2.0
> Require json as dependency only for Ruby < 2.0

- lib/twitter_cldr/data_readers/number_data_reader.rb
- lib/twitter_cldr/formatters/numbers/currency_formatter.rb
- spec/localized/localized_number_spec.rb
The currency symbol depends on the locale (e.g. USD uses "USD" not "$" in en-AU).
> Pass along locale when formatting currencies.

- twitter_cldr.gemspec
I'm working on the open source project [VersionEye](https://www.versioneye.com). By adding the license info to the gempspec it becomes available through the public RubyGems API and that way other tools like VersionEye can fetch it easier.
> Add license info to the gemspec.

- lib/twitter_cldr/tokenizers/tokenizer.rb
I was getting the following warning:
gems/twitter_cldr-4.4.2/lib/twitter_cldr/tokenizers/tokenizer.rb:49: warning: encoding option is ignored - u
`Regexp` hasn't supported the `u` option, or anything but the `n` option since Ruby 1.8
> Fix encoding warning

- lib/twitter_cldr/resources/loader.rb
- spec/resources/loader_spec.rb
I faced with encoding issue on windows. 
Code `3.localize(:zh).spellout` produce `Σ╕ë` on unix it works properly and return `三`
This PR fix encoding issue on windows
> Provide file encoding explicitly in resource loader

- lib/twitter_cldr/resources/language_codes_importer.rb
- lib/twitter_cldr/resources/postal_codes_importer.rb
- lib/twitter_cldr/resources/requirements/cldr_requirement.rb
- lib/twitter_cldr/resources/requirements/icu_requirement.rb
- lib/twitter_cldr/resources/uli/segment_exceptions_importer.rb
- spec/collation/collation_spec.rb
- spec/segmentation/break_iterator_spec.rb
- twitter_cldr.gemspec
This PR changes every instance of an http url to its https version for security reasons.
> Use https instead of http in urls

- lib/twitter_cldr.rb
- lib/twitter_cldr/shared/locale.rb
- spec/formatters/plurals/plural_formatter_spec.rb
- spec/shared/calendar_spec.rb
- spec/shared/numbers_spec.rb
- spec/twitter_cldr_spec.rb
Right now, if you use a valid BCP-47 code that has multiple parts (i.e. `de-DE`) that is unsupported, TwitterCLDR falls back to the default locale. This change has it try the language (i.e. `de`) first before falling back to default.
This change is not robust to certain edge cases. Some examples:
- `zh-Hant-TW` should fall back to `zh-Hant`, not `zh`
- `es-CR` should fall back to `es-419`, not `es`
> convert_locale falls back to language

- lib/twitter_cldr/core_ext.rb
- lib/twitter_cldr/formatters/numbers/number_formatter.rb
- spec/localized/localized_number_spec.rb
This PR adds support to BigDecimal alongside Float and Int as a class of number that can undergo localization. This is necessary in contexts where arbitrary precision numbers need to be localized.
> support BigDecimal in number localization

- lib/twitter_cldr/timezones/generic_location.rb
- lib/twitter_cldr/timezones/gmt_location.rb
- lib/twitter_cldr/timezones/iso8601_location.rb
- lib/twitter_cldr/timezones/location.rb
- lib/twitter_cldr/timezones/timezone.rb
- spec/timezones/timezone_spec.rb
We ran into an odd issue where passing certain UTC times to `display_name_for` would raise an `TZInfo::AmbiguousTime` exception. A little digging lead me to to [this issue in the `tzinfo` repo](https://github.com/tzinfo/tzinfo/issues/32). This PR addresses this issue by passing a "fallback" block to `period_for_local`.
I wasn't sure the preferred way to add tests so I added a simple "demo" one.  I'm happy to update/add more if desired.
> Fix ambiguous time issue

- lib/twitter_cldr/formatters/numbers/rbnf/rule_set.rb
BigDecimal.new was deprecated and then removed in ruby 2.7+
This replaces `BigDecimal.new()` with `BigDecimal()`
Closes #250
> Replace BigDecimal.new() with BigDecimal() for ruby 2.7+ compatibility

- README.md
- README.md.erb
- lib/twitter_cldr/shared/currencies.rb
- spec/shared/currencies_spec.rb
> Currencies#for_code returns name instead of one spelling

- twitter_cldr.gemspec
Hello!
Would be great if we could add the Github-repo to the gemspec.
Does this look okay? It is what I have used on other gems.
It will help e.g. Dependabot to include changelog in PRs.
> Adds github repo as homepage

- lib/twitter_cldr/segmentation/cj_break_engine.rb
- lib/twitter_cldr/segmentation/cursor.rb
I'm really surprised our tests didn't catch this. The code effectively reads past the end of an array because it uses the wrong counter variable as an index 🤦 
Fixes #260
> Fix bug in the CJK break engine causing an int to be compared to nil

- twitter_cldr.gemspec
I've removed the spec/ folder from the gem package to reduce its size, as it's over 30MB due to large test files. This folder, is only for testing and doesn't need to be in the packaged gem. This change lowers the package size, improving installation speed without affecting functionality.
> Exclude spec/ Folder from Gem Package to Reduce Size

- README.md
- README.md.erb
We noticed an error in the README page.
When calling `TwitterCldr::Segmentation::BreakIterator.new(:en)`, the `:use_uli_exceptions` flag seems `false` by default.
Indeed, these blocks return the same results: 
```ruby 
iterator = TwitterCldr::Segmentation::BreakIterator.new(:en)
iterator.each_sentence("I like Ms. Murphy, she's nice.") do |sentence|
puts sentence  # "I like Ms. ", "Murphy, she's nice."
end
```
```ruby
iterator = TwitterCldr::Segmentation::BreakIterator.new(:en, :use_uli_exceptions => false)
iterator.each_sentence("I like Ms. Murphy, she's nice.") do |sentence|
puts sentence  # "I like Ms. ", "Murphy, she's nice."
end
```
And when using `:use_uli_exceptions => true`, the exceptions are correctly applied:
```ruby
iterator = TwitterCldr::Segmentation::BreakIterator.new(:en, …
```
> README.md: Fix `:use_uli_exceptions` default behavior in the docs

- lib/twitter_cldr/segmentation/rule_set.rb
- spec/segmentation/break_iterator_spec.rb
Using this gem's sentence segmentation feature, we recently uncovered a bug.
With ULI rules enabled, when trying to segment into sentences a string that ends with an exception (e.g. the abbreviation "Mrs.") directly followed by a single space, we found that the segmentation returns an array in which the last sentence is missing.
```ruby
iterator = TwitterCldr::Segmentation::BreakIterator.new(:en, :use_uli_exceptions => true)
iterator.each_sentence("I like the Mrs. ").to_a # []
```
We have written the simplest possible spec for this in `spec/segmentation/break_iterator_spec.rb`:
```ruby
it "splits correctly when a string ends with an exception directly followed by a single space" do
str = "I like the Mrs. "
expect(iterator.each_sentence(str).map { |word, _, _| word }).to eq([
"I like the …
```
> Fix sentence segmentation bug

- README.md
Fix unit tests badge URL in README
- Update GitHub Actions badge URL to point to the correct twitter/twitter-cldr-rb repository
- Previously referenced camertron/rux repository which was incorrect
- Ensures badge reflects actual test status of this repository
> Fixed unit tests badge URL in README.md

- lib/twitter_cldr/formatters/calendars/date_time_formatter.rb
- lib/twitter_cldr/localized/localized_datetime.rb
- spec/localized/localized_time_spec.rb
👋 Hello again @camertron. It's Michael from `ruby-cldr` (and now Stripe). It's good to see you again. 👋  
Allow for passing in `dst` parameter into `LocalizedDateTime#to_long_s`
Fixes #279.
I changed `LocalizedDateTime#to_*_s` to accept an options hash.
Then I changed `DateTimeFormatter#timezone` to pick out the `dst` param and pass it through to `Timezone#display_name_for`
All of the existing formatter methods already take in an `options` hash. However, `timezone` was the only one that was actually doing anything with it.
You will be able to request the formatting of DST-ambiguous times using the stringify functions.
🤷 Tests pass.
> Allow for passing options into `LocalizedDateTime#to_*_s`

- README.md
- README.md.erb
Just fixing up some typos that I noticed while working on #280 
* Replaced references to the old URL for `ruby-cldr`
* Dropped references to Ruby 2.3 and 2.4 (removed in https://github.com/twitter/twitter-cldr-rb/commit/b5e206e3de01e7541446322b2116df4e6de83345) 
🤷 
🤷 Slightly cleaner README.
The URLs still work.
> README fixups
